server:
  port: 7997

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:h2:mem:bank
    username: khaled
    password: password
    driver-class-name: org.h2.Driver